project:
  type: website
  output-dir: docs
  # Explicitly tell Quarto what files to render, and what to ignore:
  render:
    - "document.ipynb"
    - "gmid/sizing_2_stage_ota.ipynb"
    - "gmid/techsweep_sg13_plots_nmos.ipynb"

  resources:
    - "cace/_docs/ota-2stage/schematic/"

website:
  title: 'Design of a 4th Order Hybrid Linkwitz-Riley Crossover Filter'

execute:
  execute: true
  freeze: true